
# flux HelmRelease crd for installing nginx ingress controller helm chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rs-helmrelease
  namespace: ns-rs
spec:
  chart:
    spec:
      chart: robot-shop
      version: 1.1.x
      interval: 1h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: rs-helmrepository
  releaseName: rs-release
  targetNamespace: ns-rs
  interval: 1h # this is for drifting of the helm created resources
  timeout: 10m
  values:
    redis:
      # Storage class to use with redis statefulset.
      storageClassName: default
  
  