
# flux HelmRelease crd for installing nginx ingress controller helm chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rs-helmrelease
  namespace: ns-rs
spec:
  chart:
    spec:
      chart: rs-chart
      version: 1.1.x
      interval: 1h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: rs-helmRepository
  releaseName: rs-release
  targetNamespace: ns-rs
  interval: 1h # this is for drifting of the helm created resources
  
  