apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multi-chart-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./templates # Ruta a tu carpeta local de charts
  values:
    image:
      repo: robotshop
      version: latest
      pullPolicy: IfNotPresent
    
    # EUM configuration
    # Provide your key and set the endpoint
    eum:
      key: null
      url: https://eum-eu-west-1.instana.io
      #url: https://eum-us-west-2.instana.io
    
    # Pod Security Policy
    psp:
      enabled: false
    
    # For the mini ones minikube, minishift set to true
    nodeport: false
    
    # "special" Openshift. Set to true when deploying to any openshift flavour
    openshift: false
    
    ocCreateRoute: false
    
    ######################################
    # Affinities for individual workloads
    # set in the following way:
    # <workload>:
    #   affinity: {}
    #   nodeSelector: {}
    #   tolerations: []
    ######################################
    
    cart: {}
    
    catalogue: {}
    
    dispatch: {}
    
    mongodb: {}
    
    mysql: {}
    
    payment:
      # Alternative payment gateway URL
      # Default is https://www.paypal.com
      gateway: null
      #gateway: https://www.worldpay.com
    
    rabbitmq: {}
    
    ratings: {}
    
    redis:
      # Storage class to use with redis statefulset.
      storageClassName: standard
    
    shipping: {}
    
    user: {}
    
    web: {}
        # Configuración de valores para tus charts
