
# flux HelmRelease crd for installing nginx ingress controller helm chart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robot-shop-whale-hrel
  namespace: robot-shop-whale
spec:
  chart:
    spec:
      chart: robot-shop
      version: 1.1.x
      interval: 1h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: robot-shop-whale-hrep
  releaseName: robot-shop-release
  targetNamespace: robot-shop-whale
  interval: 1h # this is for drifting of the helm created resources
  
  